# Site settings

title: Caderno de Estatística
tagline: Estudo Amaldiçoado de Probabilidade e Estatística
description: >- # this means to ignore newlines until "baseurl:"
  Anotações do Estudo Amaldiçoado de Probabilidade e Estatística do Vudu Reverso. Use por sua conta e risco.
baseurl: "/estudo-estatistica" # the subpath of your site, e.g. /blog
url: "http://josenaldo.github.io"

github_repository: https://github.com/josenaldo/estudo-estatistica


#Twitter
twitter:
  username: vudureverso
  card: summary_large_image

#logo
logo: "/invoca-piroto/assets/images/logo.jpg"

social:
  name: Vudu Reverso
  links:
    - https://twitter.com/vudureverso
    - https://www.facebook.com/josenaldo.matos
    - https://www.linkedin.com/in/josenaldo/
    - https://github.com/josenaldo

lang: pt-BR
author: vudureverso

# Social usernames/URLs
twitter_username: vudureverso
github_username: josenaldo
instagram_username: vudureverso
reddit_username: vudureverso
linkedin_link: https://www.linkedin.com/in/josenaldo/
facebook_link: https://www.facebook.com/josenaldo.matos
email: josenaldo@gmail.com

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
exclude: [vendor]
permalink: pretty

#Plugins
plugins:
  - jekyll-seo-tag

# Coleções
collections_dir: collections
collections:
  aulas:
    output: true
  perguntas:
    output: true

excerpt_separator: <!--more-->

# Valores default
defaults:
  - scope:
      path: ""
      type: "aulas"
    values:
      layout: "aula"
  - scope:
      path: ""
      type: "perguntas"
    values:
      layout: "pergunta"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

